### ISSUE TITLE
Attribute override in TCM-using child class results in tests being ignored

### ISSUE THREAD

**Issue by genehack** [test-class-moose/test-class-moose#35]
Code and test output can be found at https://gist.github.com/genehack/4a9c0979881ab5bd25ea.

Basically, I have a 'Base::Foo' class that uses plain Moose, and defines a required attribute called 'foo'. I also have a 'Tests::Bar' class that uses TCM, extends 'Base::Foo', and does ``has "+foo" => ( default => "baz" )``. Using the standard test runner from the documentation, that results in a '0 tests run' output.

One workaround is to make 'Tests::Bar' do ``extends 'Test::Class::Moose', 'Base::Foo';``. That's sort of ... nasty.

Another workaround is to make Base::Foo a role (using Moose::Role) and have Tests::Bar consume it. That would be acceptable (and maybe even arguably better), but this still seems like something that should either work (because it's just standard Moose crap), or be documented as not working.

**Comment by autarch** [comment]
I think the problem is that `Test::Class::Moose` should not be making itself a parent of the test classes that use it. Even if the magic is good, it'd be better as a role that gets automatically added to the classes, rather than a parent class.

That said, I'm much more of a fan of explicitness, and simply having test classes write `with 'Test::Class::Moose::Test'` or something like that would be as good as `use Test::Class::Moose` in my book.

That said, this is a big change that would require the existing behavior to continue to work through a long deprecation cycle, and I'm not sure it's worth the trouble for something that has such an easy workaround.

**Comment by Ovid** [comment]
Agreed. When I first released this, I knew we shouldn't be inheriting from `Test::Class::Moose` and that it should be a role, but multiple attempts to make it a role failed. As a result, I released it as is and hoped to add a role "option" in the future but never did.

**Comment by genehack** [comment]
Changing the documentation would be just as good as a fix I think. The main problem I had, from what I recall, was that I was doing things the way the documentation suggested I should, and it didn't work -- and, worse, the actual error was getting swallowed and I had to do a lot of digging to figure out what was going on.

**Comment by autarch** [comment]
I added a note about this in the docs for 0.61.
