### ISSUE TITLE
is there a method for doing chained tests?

### ISSUE THREAD

**Issue by jscook** [test-class-moose/test-class-moose#45]
I'm not sure it is appropriate to ask questions here, please let me know if you'd like me to move this somewhere else. I appreciate any feedback you have.

I am working on system testing a few command-line programs where the input of one depends on the output of another. This appears to be called 'chained testing':

http://xunitpatterns.com/Chained%20Tests.html

I was wondering if there was a method of doing this with Test::Class::Moose? I was not able to find anything going through the documentation and some source.

Here is an example of something similar with phpunit:

https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.test-dependencies

**Comment by Ovid** [comment]
That's very interesting. I could work something out with `test_setup` and the `$test->test_report->current_method` but that would be a bit of a hack. Otherwise, something based on new attributes would be useful, but currently, attributes aren't terribly extensible beyond what's already there. If you have some ideas on how to implement that, I'm all ears.

**Comment by autarch** [comment]
I think the easiest way to do this would be to apply a role to the `Executor` class that overrides `_tcm_test_methods_for_instance` and returns the methods in the right order. This wouldn't be terribly hard to implement, but I don't think it needs to be in the core distribution.

**Comment by jscook** [comment]
I think that sounds good Dave. I've been trying to design something Makefile-y in my head but I think that your solution would be best.

Thank you both for the feedback.
