### ISSUE TITLE
Minimum required Test::Harness would be 3.29

### ISSUE THREAD

**Issue by andk** [test-class-moose/test-class-moose#65]
As per subject. Older Test::Harness fail, sample report:

http://www.cpantesters.org/cpan/report/71836427

I have reproduced this result by downgrading to 3.28.

Best,

**Comment by autarch** [comment]
cpantesters is not loading for me, but my guess is that there's some subtle difference in the TAP output under Test2 that older Test::Harness versions cannot parse.

I'm not sure how to deal with this, since I don't want Test::Harness to be a prereq for this distro.

**Comment by autarch** [comment]
Ah, it finally loaded. This appears to be an entirely different problem than I guessed, and I also realized that Test::Harness is a prereq because of the use of TAP::Formatter::Color. I'd really like to replace that module with something else, since we're just using it to color some dots red or green. It'd be really nice to find a small module that does that in a cross-platform way.
