### ISSUE TITLE
Using MooseX::StrictConstructor in a test class breaks >= 0.77

### ISSUE THREAD

**Issue by Zhtwn** [test-class-moose/test-class-moose#68]
If any Test::Class::Moose test role uses MooseX::StrictConstructor, that role gets applied to Test::Class::Moose as well. This results in an exception, because `Role::Executor::_run_test_instances` is still passing the old config options to `Test::Class::Moose->new`, but as of commit 12d14a0bc these options are no longer being stripped in `Test::Class::Moose::BUILDARGS`.

[tcm-strictconstructor-bug.pl.txt](https://github.com/test-class-moose/test-class-moose/files/456754/tcm-strictconstructor-bug.pl.txt)
[tcm-strictconstructor-bug.pl.out.txt](https://github.com/test-class-moose/test-class-moose/files/456756/tcm-strictconstructor-bug.pl.out.txt)

As an aside, I wonder if there are other MooseX roles that could be applied to TCM roles that could break the TCM core...

**Comment by autarch** [comment]
I think the fix is probably to stop passing all that stuff to the constructor for test classes. @Ovid, what do you think? Right now we pass all of `$self->test_configuration->args` to the constructor for each test class. The `$self` here is a `Test::Class::Moose::Executor::Sequential` or `::Parallel` object.

This used to work because `Test::Class::Moose` itself accepted all of the arguments that were in the test config.

Do you remember what the intention was here? It's hard to see how these arguments could actually be used by a test class as opposed to by `Test::Class::Moose` itself (back when TCM was both parent and runner).

**Comment by Ovid** [comment]
@autarch: As I recall, it was a backwards-compatibility shim from when I didn't have configuration information properly separated, but back in 2012, I separated the configuration out and later renamed it to `test_configuration`. It's probably safe to fix now.
